# Generated by Django 3.1.4 on 2020-12-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
