# Generated by Django 3.1.4 on 2020-12-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='status',
            field=models.CharField(choices=[('normal', '보이게'), ('banned', '안보이게')], max_length=6),
        ),
    ]
