# Generated by Django 3.1.4 on 2020-12-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20201209_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='status',
            field=models.CharField(choices=[('normal', '보이게'), ('banned', '안보이게')], default='normal', max_length=6),
        ),
    ]
