# Generated by Django 3.1.4 on 2020-12-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20201209_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='color_code',
            field=models.CharField(default='FF0000', max_length=6),
        ),
    ]
